name: test-env
dependencies:
	-python==3.7
	-scipy==1.2.1
	-Pillow==9.3.0
	-opencv-python-headless==4.5.4.58
	-absl-py==1.3.0
	-astor==0.8.1
	-certifi==2022.9.24
	-cycler==0.11.0
	-fonttools==4.38.0
	-gast==0.2.2
	-google-pasta==0.2.0
	-grpcio==1.51.1
	-h5py==3.7.0
	-importlib-metadata==5.1.0
	-install==1.3.5
	-Keras-Applications==1.0.8
	-Keras-Preprocessing==1.1.2
	-kiwisolver==1.4.4
	-Markdown==3.4.1
	-MarkupSafe==2.1.1
	-matplotlib==3.5.3
	-numpy==1.21.6
	-opencv-python==4.6.0.66
	-opt-einsum==3.3.0
	-packaging==21.3
	-pip==22.2.2
	-protobuf==3.20.1
	-pyparsing==3.0.9
	-python-dateutil==2.8.2
	-setuptools==65.5.0
	-six==1.16.0
	-tensorboard==1.15.0
	-tensorflow-estimator==1.15.1
	-tensorflow==1.15.0
	-termcolor==2.1.1
	-typing_extensions==4.4.0
	-Werkzeug==2.2.2
	-wheel==0.37.1
	-wincertstore==0.2
	-wrapt==1.14.1
	-zipp==3.11.0